# The time between each run (in seconds)
delay: 5

# Choose from the list what you want enabled
# If you would like something enabled, put "true"
# If you wouldn't like it enabled, put "false"

# Lightning will randomly strike down in a 3 block radius of a player
lightning: true

# It will rain dogs!
# No cats, because they don't take fall damage, lol.
rain-dogs: true

# Creepers will randomly spawn in a 20 block radius at any time
creeper: true

# Give the creeper a change to be a charged creeper?
# If creeper isn't true, this one won't work.
charged-creeper: true

# In a 10 block radius of a player,
# If a 4x2x4 is found of stone, a block of lava will spawn
lava: true

# While wandering around in grass, podzol will spawn,
# and the player will feel relieved
poop: true

# While swimming, you might just be pushed up by a wave!
waterwave: true

# Sinkholes : Would you like there to be sinkholes in Minecraft?
# Sizes will be expressed in 3x3, 5x5, and 10x10.
# The larger, the more rare of it occuring.
# There's also a chance that a sinkhole will decide not to appear
sinkholes: true