# The time between each run.
# Keep in mind, 20 = 1 second.
delay: 100

# Choose from the list what you want enabled
# If you would like something enabled, put "true"
# If you wouldn't like it enabled, put "false"

# Lightning will randomly strike down in a 3 block radius of a player
lightning: true

# It will rain dogs!
# No cats, because they don't take fall damage, lol.
rain-dogs: true

# Creepers will randomly spawn in a 20 block radius at any time
creeper: true

# Give the creeper a change to be a charged creeper?
# If creeper isn't true, this one won't work.
charged-creeper: true

# In a 10 block radius of a player,
# If a 4x2x4 is found of stone, a block of lava will spawn
lava: true

# While wandering around in grass, podzol will spawn,
# and the player will feel relieved
poop: true

# While swimming, you might just be pushed up by a wave!
waterwave: true

# Sinkholes : Would you like there to be sinkholes in Minecraft?
# Sizes will be expressed in 3x3, 5x5, and 10x10.
# The larger, the more rare of it occuring.
# There's also a chance that a sinkhole will decide not to appear
sinkholes: true

# Sometimes, when you engage into hitting an entity, you get to
# fly backwards! Be careful where you attack!
take-entity-velocity: true

# Sometimes, one bonus chest when the world first loads up isn't enough.
# Let's help out the players, and give them some helpful items!
# There are 3 levels: poor (lowest class), feasible (middle class), rich (highest class)
bonus-chests: true

# You become lifted off of the ground momentarily because of a strong breeze.
wind: true

# Allow angry wolves to randomly spawn near a player, and attack them.
# This is because man's best friend isn't always their best friend, and
# the wolf needs to protect its territory!
angry-wolf: true